//INICIAR

//LER 10 IDADES

//LER AUTORIZAÇÕES

//VERIFICAR SE É MAIOR DE IDADE E SE TEM AUTORIZAÇÃO

//SE AS 2 CONDIÇÕES FOREM ATINGIDAS - EXIBIR: ENTRADA LIBERADA
//CASO CONTRÁRIO - EXIBIR: ENTRADA NEGADA

//CONTAR QUANTIDADE DE ENTRADAS LIBERADAS
//CONTAR QUANTIDADE DE ENTRADAS NEGADAS
//CONTAR A MAIOR IDADE REGISTRADAS
//TIRAR A MÉDIA DAS IDADES REGISTRADAS

//EXIBIR A QUANTIDADE DE ENTRADAS LIBERADAS
//EXIBIR A QUANTIDADE DE ENTRADAS NEGADAS
//EXIBIR A MAIOR IDADE REGISTRADA
//EXIBIR A MÉDIA DAS IDADES REGISTRADA
